name: make-lint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2.4.2
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: '16'
    - run: make install
    - run: make lint
      