name: make-lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - run: make install
    - run: make lint
  # build:
  #   runs-on: ubuntu-latest
  #   steps: 
  #   - uses: actions/checkout@v2
  #       with:
  #         node-version: '16.x'
  #         cache: npm
  #   - run:
  #     make lint